/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author ciclesgs
 */
public class MainPage extends javax.swing.JFrame {
    
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        
        initComponents();
        jPanelMenu.setVisible(true);
        jPanelNewAuthor.setVisible(false);
        jPanelNewMember.setVisible(false);
        jPanelNewBook.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNewBook = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btCreateNewBook = new javax.swing.JButton();
        txtFBookTitle = new javax.swing.JTextField();
        btBookGoToMenu = new javax.swing.JButton();
        txtFBookAuthor = new javax.swing.JTextField();
        jPanelNewMember = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCreateNewMember = new javax.swing.JButton();
        txtFMemberName = new javax.swing.JTextField();
        btMemberGoToMenu = new javax.swing.JButton();
        txtFMembersLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFMembersPasword = new javax.swing.JTextField();
        jPanelNewAuthor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCreateNewAuthor = new javax.swing.JButton();
        txtFAuthorName = new javax.swing.JTextField();
        txtFAutorLastname = new javax.swing.JTextField();
        btAuthrosGoToMenu = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        btMenuNewBuck1 = new javax.swing.JButton();
        btMenuNewAuthor1 = new javax.swing.JButton();
        btMenuNewLoan = new javax.swing.JButton();
        btMenuNewMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNewBook.setBackground(new java.awt.Color(67, 75, 77));

        jLabel6.setText("title:");

        jLabel7.setText("author");

        btCreateNewBook.setBackground(new java.awt.Color(40, 40, 40));
        btCreateNewBook.setText("create");
        btCreateNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateNewBookActionPerformed(evt);
            }
        });

        btBookGoToMenu.setBackground(new java.awt.Color(40, 40, 40));
        btBookGoToMenu.setText("menu");
        btBookGoToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBookGoToMenuActionPerformed(evt);
            }
        });

        txtFBookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFBookAuthorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewBookLayout = new javax.swing.GroupLayout(jPanelNewBook);
        jPanelNewBook.setLayout(jPanelNewBookLayout);
        jPanelNewBookLayout.setHorizontalGroup(
            jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBookGoToMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNewBookLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCreateNewBook)
                    .addGroup(jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelNewBookLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelNewBookLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(75, 75, 75)
                            .addComponent(txtFBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanelNewBookLayout.setVerticalGroup(
            jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewBookLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btBookGoToMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelNewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btCreateNewBook)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanelNewMember.setBackground(new java.awt.Color(67, 75, 77));

        jLabel3.setText("name:");

        jLabel4.setText("lastname");

        btCreateNewMember.setBackground(new java.awt.Color(40, 40, 40));
        btCreateNewMember.setText("create");
        btCreateNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateNewMemberActionPerformed(evt);
            }
        });

        btMemberGoToMenu.setBackground(new java.awt.Color(40, 40, 40));
        btMemberGoToMenu.setText("menu");
        btMemberGoToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemberGoToMenuActionPerformed(evt);
            }
        });

        txtFMembersLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFMembersLastnameActionPerformed(evt);
            }
        });

        jLabel5.setText("pasword");

        txtFMembersPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFMembersPaswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewMemberLayout = new javax.swing.GroupLayout(jPanelNewMember);
        jPanelNewMember.setLayout(jPanelNewMemberLayout);
        jPanelNewMemberLayout.setHorizontalGroup(
            jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMemberGoToMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCreateNewMember)
                    .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFMembersPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFMembersLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(75, 75, 75)
                            .addComponent(txtFMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanelNewMemberLayout.setVerticalGroup(
            jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewMemberLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btMemberGoToMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFMembersLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanelNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFMembersPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btCreateNewMember)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanelNewAuthor.setBackground(new java.awt.Color(67, 75, 77));

        jLabel1.setText("name:");

        jLabel2.setText("lastname");

        btCreateNewAuthor.setBackground(new java.awt.Color(40, 40, 40));
        btCreateNewAuthor.setText("create");
        btCreateNewAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateNewAuthorActionPerformed(evt);
            }
        });

        txtFAutorLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAutorLastnameActionPerformed(evt);
            }
        });

        btAuthrosGoToMenu.setBackground(new java.awt.Color(40, 40, 40));
        btAuthrosGoToMenu.setText("menu");
        btAuthrosGoToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAuthrosGoToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewAuthorLayout = new javax.swing.GroupLayout(jPanelNewAuthor);
        jPanelNewAuthor.setLayout(jPanelNewAuthorLayout);
        jPanelNewAuthorLayout.setHorizontalGroup(
            jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewAuthorLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCreateNewAuthor)
                    .addGroup(jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelNewAuthorLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFAutorLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelNewAuthorLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(75, 75, 75)
                            .addComponent(txtFAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelNewAuthorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAuthrosGoToMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNewAuthorLayout.setVerticalGroup(
            jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewAuthorLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btAuthrosGoToMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelNewAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFAutorLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btCreateNewAuthor)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanelMenu.setBackground(new java.awt.Color(67, 75, 77));

        btMenuNewBuck1.setBackground(new java.awt.Color(40, 40, 40));
        btMenuNewBuck1.setText("new boock");
        btMenuNewBuck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuNewBuck1ActionPerformed(evt);
            }
        });

        btMenuNewAuthor1.setBackground(new java.awt.Color(40, 40, 40));
        btMenuNewAuthor1.setText("new author");
        btMenuNewAuthor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuNewAuthor1ActionPerformed(evt);
            }
        });

        btMenuNewLoan.setBackground(new java.awt.Color(40, 40, 40));
        btMenuNewLoan.setText("new loan");

        btMenuNewMember.setBackground(new java.awt.Color(40, 40, 40));
        btMenuNewMember.setText("new member");
        btMenuNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuNewMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMenuNewLoan)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(btMenuNewMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btMenuNewBuck1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btMenuNewAuthor1)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMenuNewBuck1)
                    .addComponent(btMenuNewMember)
                    .addComponent(btMenuNewAuthor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btMenuNewLoan)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanelNewAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelNewMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelNewBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanelNewAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelNewMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelNewBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuNewBuck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuNewBuck1ActionPerformed
        jPanelNewBook.setVisible(true);
        jPanelMenu.setVisible(false);
    }//GEN-LAST:event_btMenuNewBuck1ActionPerformed

    private void btCreateNewAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateNewAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCreateNewAuthorActionPerformed

    private void btMenuNewAuthor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuNewAuthor1ActionPerformed

        jPanelNewAuthor.setVisible(true);
        jPanelMenu.setVisible(false);
        
    }//GEN-LAST:event_btMenuNewAuthor1ActionPerformed

    private void txtFAutorLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAutorLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAutorLastnameActionPerformed

    private void btAuthrosGoToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAuthrosGoToMenuActionPerformed
        jPanelMenu.setVisible(true);
        jPanelNewAuthor.setVisible(false);
        
    }//GEN-LAST:event_btAuthrosGoToMenuActionPerformed

    private void btCreateNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateNewMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCreateNewMemberActionPerformed

    private void txtFMembersLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFMembersLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMembersLastnameActionPerformed

    private void btMemberGoToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemberGoToMenuActionPerformed
        jPanelMenu.setVisible(true);
        jPanelNewMember.setVisible(false);
    }//GEN-LAST:event_btMemberGoToMenuActionPerformed

    private void txtFMembersPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFMembersPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMembersPaswordActionPerformed

    private void btMenuNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuNewMemberActionPerformed
        jPanelNewMember.setVisible(true);
        jPanelMenu.setVisible(false);
    }//GEN-LAST:event_btMenuNewMemberActionPerformed

    private void btCreateNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateNewBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCreateNewBookActionPerformed

    private void btBookGoToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBookGoToMenuActionPerformed
        jPanelMenu.setVisible(true);
        jPanelNewBook.setVisible(false);
    }//GEN-LAST:event_btBookGoToMenuActionPerformed

    private void txtFBookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFBookAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBookAuthorActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAuthrosGoToMenu;
    private javax.swing.JButton btBookGoToMenu;
    private javax.swing.JButton btCreateNewAuthor;
    private javax.swing.JButton btCreateNewBook;
    private javax.swing.JButton btCreateNewMember;
    private javax.swing.JButton btMemberGoToMenu;
    private javax.swing.JButton btMenuNewAuthor1;
    private javax.swing.JButton btMenuNewBuck1;
    private javax.swing.JButton btMenuNewLoan;
    private javax.swing.JButton btMenuNewMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNewAuthor;
    private javax.swing.JPanel jPanelNewBook;
    private javax.swing.JPanel jPanelNewMember;
    private javax.swing.JTextField txtFAuthorName;
    private javax.swing.JTextField txtFAutorLastname;
    private javax.swing.JTextField txtFBookAuthor;
    private javax.swing.JTextField txtFBookTitle;
    private javax.swing.JTextField txtFMemberName;
    private javax.swing.JTextField txtFMembersLastname;
    private javax.swing.JTextField txtFMembersPasword;
    // End of variables declaration//GEN-END:variables
}
